/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Wed Aug  1 10:33:56 2012
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


